### ISSUE TITLE
Archive site/redirect to heroku site

### ISSUE THREAD

**Issue by KendallDoesCoding** [TechStudent11/techstudent11.github.io#3]
As, you stated that you have a better portfolio heroku site, I suggest you either:
1. Archive repo, delete from github pages
2. Redirect to your new portfolio heroku site

_Originally posted by @TechStudent11 in https://github.com/TechStudent11/techstudent11.github.io/issues/2#issuecomment-986272104_

**Comment by TechStudent10** [comment]
I think I'll go with 2. Let me just do that real quick...

**Comment by TechStudent10** [comment]
This has been fixed as of https://github.com/TechStudent11/techstudent11.github.io/commit/c14f175d73ee26bee7f1d59103860aa67bee241d

**Comment by KendallDoesCoding** [comment]
Cool!
